// Code generated by capnpc-go. DO NOT EDIT.

package generated

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type User capnp.Struct

// User_TypeID is the unique identifier for the type User.
const User_TypeID = 0xa73aed35789989ec

func NewUser(s *capnp.Segment) (User, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return User(st), err
}

func NewRootUser(s *capnp.Segment) (User, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return User(st), err
}

func ReadRootUser(msg *capnp.Message) (User, error) {
	root, err := msg.Root()
	return User(root.Struct()), err
}

func (s User) String() string {
	str, _ := text.Marshal(0xa73aed35789989ec, capnp.Struct(s))
	return str
}

func (s User) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (User) DecodeFromPtr(p capnp.Ptr) User {
	return User(capnp.Struct{}.DecodeFromPtr(p))
}

func (s User) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s User) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s User) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s User) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s User) Id() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s User) SetId(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s User) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s User) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s User) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s User) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s User) Age() uint8 {
	return capnp.Struct(s).Uint8(8)
}

func (s User) SetAge(v uint8) {
	capnp.Struct(s).SetUint8(8, v)
}

func (s User) Active() bool {
	return capnp.Struct(s).Bit(72)
}

func (s User) SetActive(v bool) {
	capnp.Struct(s).SetBit(72, v)
}

// User_List is a list of User.
type User_List = capnp.StructList[User]

// NewUser creates a new list of User.
func NewUser_List(s *capnp.Segment, sz int32) (User_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[User](l), err
}

// User_Future is a wrapper for a User promised by a client call.
type User_Future struct{ *capnp.Future }

func (f User_Future) Struct() (User, error) {
	p, err := f.Future.Ptr()
	return User(p.Struct()), err
}

const schema_bf5147d3e5f3e4a1 = "x\xda\x14\xc8\xa1N\xc3P\x14\x06\xe0\xff?\xa7\xebX" +
	"2\xc2.\xb9\x0a\x89$\x01\x82\xc0\xd4\x0c\x07\x92#p" +
	"\x08n\xba\x1b\xda\x84.\xcdZ\x08\x0a\xcf# Q\xbc" +
	"\x03\xa6\x0a\x81@\xf1\x0a\x10\x0c(\x1e\xa0K\xd5\x97|" +
	"\xb3\x87\x93\xe4h\xb3#\xc4\xfc(\xed\x7f\x1f\x9f\xee\x8f" +
	"\xff\xb2\x17\xd86\xa5\x7f\xfe\xfa\xff\xfe<\xb5\x0e#\x8e" +
	"\x01\xf7\xf6\xea>\x06\xdf\x7f\xb0\xdf7y\x11\xabpx" +
	"\xcb&\xae\x0e\xf2P/\xe7uv\xd1\xc4\xd59i3" +
	"M\x80\x84\x80\x0b;\x80]*\xad\x10\x92\x9e\xc3\xc5=" +
	"\xc0\xae\x94v#t\xb2\xe1)\x80+w\x01[(\xad" +
	"\x16:=\xf3T\xc0U\x19`\x85\xd2Z\xa1\x96\x0bN" +
	" \x9c\x80[\xcbPEN!\x9c\x82\xe3p\x1d\x99B" +
	"\x98\x82\xf3\x90\xb7\xe5]$!$\xb8\x1e\x00a\x11-" +
	"z"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_bf5147d3e5f3e4a1,
		Nodes: []uint64{
			0xa73aed35789989ec,
		},
		Compressed: true,
	})
}
