// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	packetProgPacketFilter = "packet_filter"
)

// loadPacket returns the embedded CollectionSpec for packet.
func loadPacket() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PacketBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load packet: %w", err)
	}

	return spec, err
}

// loadPacketObjects loads packet and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*packetObjects
//	*packetPrograms
//	*packetMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPacketObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadPacket()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// packetSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type packetSpecs struct {
	packetProgramSpecs
	packetMapSpecs
	packetVariableSpecs
}

// packetProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type packetProgramSpecs struct {
	PacketFilter *ebpf.ProgramSpec `ebpf:"packet_filter"`
}

// packetMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type packetMapSpecs struct {
}

// packetVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type packetVariableSpecs struct {
}

// packetObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPacketObjects or ebpf.CollectionSpec.LoadAndAssign.
type packetObjects struct {
	packetPrograms
	packetMaps
	packetVariables
}

func (o *packetObjects) Close() error {
	return _PacketClose(
		&o.packetPrograms,
		&o.packetMaps,
	)
}

// packetMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPacketObjects or ebpf.CollectionSpec.LoadAndAssign.
type packetMaps struct {
}

func (m *packetMaps) Close() error {
	return _PacketClose()
}

// packetVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPacketObjects or ebpf.CollectionSpec.LoadAndAssign.
type packetVariables struct {
}

// packetPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPacketObjects or ebpf.CollectionSpec.LoadAndAssign.
type packetPrograms struct {
	PacketFilter *ebpf.Program `ebpf:"packet_filter"`
}

func (p *packetPrograms) Close() error {
	return _PacketClose(
		p.PacketFilter,
	)
}

func _PacketClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed packet_bpfel.o
var _PacketBytes []byte
